/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hauntedMansionApp.FileManager;
import hauntedMansionApp.*;
import java.awt.CardLayout;
import java.awt.Label;
import java.awt.Panel;
import java.io.File;
import javax.swing.JFileChooser;
import java.util.Iterator;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author Ricardo Cardoso Abílio Castro
 */
public class HauntedFrame extends javax.swing.JFrame {

    LinkedMap teste;
    Aposento[] map;

    /**
     * Creates new form Container
     */
    public HauntedFrame() {
        initComponents();
        teste = new LinkedMap();
    }

    public void playSound(String soundName) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        menuPanel = new javax.swing.JPanel();
        carregarJsonBtn = new javax.swing.JButton();
        verJsonBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        simulationBtn = new javax.swing.JButton();
        secretRoomsBtn = new javax.swing.JButton();
        roomsGhostsBtn = new javax.swing.JButton();
        titleBtn = new javax.swing.JButton();
        loadGameLabel = new javax.swing.JLabel();
        playGameLabel = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        howToPlayBtn = new javax.swing.JButton();
        creditBtn = new javax.swing.JButton();
        cardLayoutPanel = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        labelBack = new javax.swing.JLabel();
        jsonFileUploadPanel = new javax.swing.JPanel();
        pathLabel = new javax.swing.JTextField();
        sendJsonBtn = new javax.swing.JButton();
        fileChooserPanel = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();
        fileSuccessLabel = new javax.swing.JLabel();
        uploadJsonLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        simulationStartBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        caminhoSimulationLabel = new javax.swing.JLabel();
        simulationLabel = new javax.swing.JLabel();
        simulationTitleLabel = new javax.swing.JLabel();
        grafoConexoPanel = new javax.swing.JPanel();
        grafoConexoLabel = new javax.swing.JLabel();
        grafoConexoBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jsonFileViewerPanel = new javax.swing.JPanel();
        jsonFileViewerLabel = new javax.swing.JLabel();
        jsonViewerTitleLabel = new javax.swing.JLabel();
        creditsPanel = new javax.swing.JPanel();
        creditsLabel = new javax.swing.JLabel();
        ricardoLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));

        carregarJsonBtn.setBackground(new java.awt.Color(0, 0, 0));
        carregarJsonBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        carregarJsonBtn.setForeground(new java.awt.Color(255, 0, 0));
        carregarJsonBtn.setText("UPLOAD JSON");
        carregarJsonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarJsonBtnActionPerformed(evt);
            }
        });

        verJsonBtn.setBackground(new java.awt.Color(0, 0, 0));
        verJsonBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        verJsonBtn.setForeground(new java.awt.Color(255, 0, 0));
        verJsonBtn.setText("JSON VIEWER");
        verJsonBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verJsonBtnMouseClicked(evt);
            }
        });
        verJsonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verJsonBtnActionPerformed(evt);
            }
        });

        playBtn.setBackground(new java.awt.Color(0, 0, 0));
        playBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        playBtn.setForeground(new java.awt.Color(255, 0, 0));
        playBtn.setText("PLAY");
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtnMouseClicked(evt);
            }
        });
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        simulationBtn.setBackground(new java.awt.Color(0, 0, 0));
        simulationBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        simulationBtn.setForeground(new java.awt.Color(255, 0, 0));
        simulationBtn.setText("SIMULATION");
        simulationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulationBtnMouseClicked(evt);
            }
        });
        simulationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationBtnActionPerformed(evt);
            }
        });

        secretRoomsBtn.setBackground(new java.awt.Color(0, 0, 0));
        secretRoomsBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        secretRoomsBtn.setForeground(new java.awt.Color(255, 0, 0));
        secretRoomsBtn.setText("SECRET ROOMS");
        secretRoomsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secretRoomsBtnMouseClicked(evt);
            }
        });
        secretRoomsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretRoomsBtnActionPerformed(evt);
            }
        });

        roomsGhostsBtn.setBackground(new java.awt.Color(0, 0, 0));
        roomsGhostsBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        roomsGhostsBtn.setForeground(new java.awt.Color(255, 0, 0));
        roomsGhostsBtn.setText("ROOMS W/ GHOSTS");
        roomsGhostsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsGhostsBtnActionPerformed(evt);
            }
        });

        titleBtn.setBackground(new java.awt.Color(0, 0, 0));
        titleBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        titleBtn.setForeground(new java.awt.Color(255, 0, 0));
        titleBtn.setText("HAUNTED MANSION GAME");
        titleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleBtnMouseClicked(evt);
            }
        });
        titleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleBtnActionPerformed(evt);
            }
        });

        loadGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadGameLabel.setText("_______ JSON FILE / LOAD GAME _______");

        playGameLabel.setForeground(new java.awt.Color(255, 255, 255));
        playGameLabel.setText("____________ PLAY GAME ____________");

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 0, 0));
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        howToPlayBtn.setBackground(new java.awt.Color(0, 0, 0));
        howToPlayBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        howToPlayBtn.setForeground(new java.awt.Color(255, 0, 0));
        howToPlayBtn.setText("HOW TO PLAY");
        howToPlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayBtnActionPerformed(evt);
            }
        });

        creditBtn.setBackground(new java.awt.Color(0, 0, 0));
        creditBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        creditBtn.setForeground(new java.awt.Color(255, 0, 0));
        creditBtn.setText("CREDITS");
        creditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(howToPlayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadGameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verJsonBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulationBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secretRoomsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomsGhostsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carregarJsonBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playGameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadGameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carregarJsonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verJsonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playGameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secretRoomsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomsGhostsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardLayoutPanel.setPreferredSize(new java.awt.Dimension(1000, 670));
        cardLayoutPanel.setLayout(new java.awt.CardLayout());

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1211, 700));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        welcomeLabel.setFont(new java.awt.Font("October Crow", 1, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 0, 0));
        welcomeLabel.setText("WELCOME TO HAUNTED MANSION GAME");

        ImageIcon icon = new ImageIcon("HauntedImg02.png");
        labelBack.setIcon(icon);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(welcomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cardLayoutPanel.add(backgroundPanel, "card1");

        jsonFileUploadPanel.setBackground(new java.awt.Color(0, 0, 0));

        pathLabel.setText("Path");
        pathLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathLabelMouseClicked(evt);
            }
        });
        pathLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathLabelActionPerformed(evt);
            }
        });

        sendJsonBtn.setBackground(new java.awt.Color(0, 0, 0));
        sendJsonBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        sendJsonBtn.setForeground(new java.awt.Color(255, 0, 0));
        sendJsonBtn.setText("Enviar");
        sendJsonBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendJsonBtnMouseClicked(evt);
            }
        });
        sendJsonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendJsonBtnActionPerformed(evt);
            }
        });

        fileChooserPanel.setBackground(new java.awt.Color(0, 0, 0));

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileChooserPanelLayout = new javax.swing.GroupLayout(fileChooserPanel);
        fileChooserPanel.setLayout(fileChooserPanelLayout);
        fileChooserPanelLayout.setHorizontalGroup(
            fileChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileChooserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fileChooserPanelLayout.setVerticalGroup(
            fileChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileChooserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileSuccessLabel.setFont(new java.awt.Font("October Crow", 1, 24)); // NOI18N
        fileSuccessLabel.setForeground(new java.awt.Color(0, 153, 0));
        fileSuccessLabel.setText("File Uploaded Successfully");
        fileSuccessLabel.setVisible(false);

        uploadJsonLabel.setFont(new java.awt.Font("October Crow", 1, 36)); // NOI18N
        uploadJsonLabel.setForeground(new java.awt.Color(255, 0, 0));
        uploadJsonLabel.setText("UPLOAD JSON");

        javax.swing.GroupLayout jsonFileUploadPanelLayout = new javax.swing.GroupLayout(jsonFileUploadPanel);
        jsonFileUploadPanel.setLayout(jsonFileUploadPanelLayout);
        jsonFileUploadPanelLayout.setHorizontalGroup(
            jsonFileUploadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jsonFileUploadPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jsonFileUploadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fileChooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jsonFileUploadPanelLayout.createSequentialGroup()
                        .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendJsonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jsonFileUploadPanelLayout.createSequentialGroup()
                        .addComponent(fileSuccessLabel)
                        .addGap(16, 16, 16)))
                .addGap(64, 64, 64))
            .addGroup(jsonFileUploadPanelLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(uploadJsonLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jsonFileUploadPanelLayout.setVerticalGroup(
            jsonFileUploadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jsonFileUploadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uploadJsonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jsonFileUploadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pathLabel)
                    .addComponent(sendJsonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileSuccessLabel)
                .addGap(70, 70, 70))
        );

        cardLayoutPanel.add(jsonFileUploadPanel, "card2");

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        simulationStartBtn.setBackground(new java.awt.Color(0, 0, 0));
        simulationStartBtn.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        simulationStartBtn.setForeground(new java.awt.Color(255, 0, 0));
        simulationStartBtn.setText("START");
        simulationStartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulationStartBtnMouseClicked(evt);
            }
        });
        simulationStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationStartBtnActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        caminhoSimulationLabel.setFont(new java.awt.Font("October Crow", 0, 24)); // NOI18N
        caminhoSimulationLabel.setText("Caminho:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caminhoSimulationLabel)
                .addGap(56, 56, 56)
                .addComponent(simulationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(simulationLabel))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(caminhoSimulationLabel)))
                .addContainerGap(514, Short.MAX_VALUE))
        );

        simulationTitleLabel.setFont(new java.awt.Font("October Crow", 1, 36)); // NOI18N
        simulationTitleLabel.setForeground(new java.awt.Color(255, 0, 0));
        simulationTitleLabel.setText("SIMULATION");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(simulationTitleLabel)
                        .addGap(0, 404, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(simulationTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simulationStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardLayoutPanel.add(jPanel7, "card4");

        grafoConexoBtn.setText("Verificar");
        grafoConexoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafoConexoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grafoConexoPanelLayout = new javax.swing.GroupLayout(grafoConexoPanel);
        grafoConexoPanel.setLayout(grafoConexoPanelLayout);
        grafoConexoPanelLayout.setHorizontalGroup(
            grafoConexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafoConexoPanelLayout.createSequentialGroup()
                .addGroup(grafoConexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grafoConexoPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(grafoConexoLabel))
                    .addGroup(grafoConexoPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(grafoConexoBtn)))
                .addContainerGap(816, Short.MAX_VALUE))
        );
        grafoConexoPanelLayout.setVerticalGroup(
            grafoConexoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafoConexoPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(grafoConexoLabel)
                .addGap(44, 44, 44)
                .addComponent(grafoConexoBtn)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(grafoConexoPanel, "card5");

        jButton17.setText("Mostrar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jTextField6.setText("id");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel35)))
                .addContainerGap(867, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton17)
                .addGap(283, 283, 283))
        );

        cardLayoutPanel.add(jPanel11, "card7");

        jButton18.setText("Mostrar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTextField7.setText("id");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel36)))
                .addContainerGap(866, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(41, 41, 41)
                .addComponent(jButton18)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(jPanel12, "card8");

        jButton19.setText("Mostrar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jTextField8.setText("id");

        jTextField9.setText("    ");

        jLabel15.setText("Empresa");

        jLabel16.setText("ID");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton19))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel14)))
                .addContainerGap(697, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel14)
                .addGap(111, 111, 111)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addComponent(jButton19)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(jPanel13, "card9");

        jTextField10.setText("empresa");

        jTextField11.setText("empresa");
        jTextField11.setToolTipText("");

        jLabel17.setText("Empresa A");

        jLabel18.setText("Empresa B");

        jButton20.setText("Mostrar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel19))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton20)))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(31, 31, 31)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jButton20)
                .addGap(173, 173, 173))
        );

        cardLayoutPanel.add(jPanel14, "card10");

        jTextField12.setText("ID");

        jTextField13.setText("Skill");

        jLabel20.setText("ID");

        jLabel21.setText("Skill");

        jButton21.setText("Mostrar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton21)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel26)))
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel26)
                .addGap(38, 38, 38)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(34, 34, 34)
                .addComponent(jButton21)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(jPanel15, "card11");

        jsonFileViewerPanel.setBackground(new java.awt.Color(0, 0, 0));

        jsonFileViewerLabel.setText("jsonFileViewerLabel");
        jsonFileViewerLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jsonViewerTitleLabel.setFont(new java.awt.Font("October Crow", 1, 36)); // NOI18N
        jsonViewerTitleLabel.setForeground(new java.awt.Color(255, 0, 0));
        jsonViewerTitleLabel.setText("JSON VIEWER");

        javax.swing.GroupLayout jsonFileViewerPanelLayout = new javax.swing.GroupLayout(jsonFileViewerPanel);
        jsonFileViewerPanel.setLayout(jsonFileViewerPanelLayout);
        jsonFileViewerPanelLayout.setHorizontalGroup(
            jsonFileViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jsonFileViewerPanelLayout.createSequentialGroup()
                .addContainerGap(405, Short.MAX_VALUE)
                .addComponent(jsonViewerTitleLabel)
                .addGap(416, 416, 416))
            .addGroup(jsonFileViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsonFileViewerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jsonFileViewerPanelLayout.setVerticalGroup(
            jsonFileViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jsonFileViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsonViewerTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jsonFileViewerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardLayoutPanel.add(jsonFileViewerPanel, "card13");

        creditsPanel.setBackground(new java.awt.Color(0, 0, 0));

        creditsLabel.setFont(new java.awt.Font("October Crow", 1, 52)); // NOI18N
        creditsLabel.setForeground(new java.awt.Color(255, 0, 0));
        creditsLabel.setText("CREDITS");

        ricardoLabel.setFont(new java.awt.Font("October Crow", 1, 48)); // NOI18N
        ricardoLabel.setForeground(new java.awt.Color(255, 0, 0));
        ricardoLabel.setText("RICARDO PEREIRA - 8170485");

        jLabel25.setFont(new java.awt.Font("October Crow", 1, 48)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("VITOR SANTOS - 8170312");

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(creditsLabel)
                .addGap(407, 407, 407))
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditsPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(ricardoLabel))
                    .addGroup(creditsPanelLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel25)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditsLabel)
                .addGap(167, 167, 167)
                .addComponent(ricardoLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(creditsPanel, "card14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarJsonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarJsonBtnActionPerformed
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card2");
    }//GEN-LAST:event_carregarJsonBtnActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void titleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleBtnActionPerformed
        /*jPanel3.setVisible(false);
            jPanel2.setVisible(false);
                    jPanel4.setVisible(true);*/
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card1");
        playSound("ButtonSound.wav");
        playSound("Ghost.wav");
    }//GEN-LAST:event_titleBtnActionPerformed

    private void titleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_titleBtnMouseClicked

    private void verJsonBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verJsonBtnMouseClicked

    }//GEN-LAST:event_verJsonBtnMouseClicked

    private void secretRoomsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretRoomsBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
    }//GEN-LAST:event_secretRoomsBtnActionPerformed

    private void verJsonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verJsonBtnActionPerformed
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card13");

        // TODO add your handling code here:
        //Declaração de variáveis auxiliares
        int i = 0;

        //Imprime na consola o Grafo Mapa Completo
        while (i < map.length) {
            System.out.println(map[i].toString());
            System.out.println("");
            i++;

            jsonFileViewerLabel.setText(map[i].toString());
        }


    }//GEN-LAST:event_verJsonBtnActionPerformed

    private void simulationBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationBtnMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card5");
    }//GEN-LAST:event_simulationBtnMouseClicked

    private void secretRoomsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secretRoomsBtnMouseClicked
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card7");
    }//GEN-LAST:event_secretRoomsBtnMouseClicked

    private void playBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseClicked
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card4");
    }//GEN-LAST:event_playBtnMouseClicked

    private void roomsGhostsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsGhostsBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card11");
    }//GEN-LAST:event_roomsGhostsBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
    }//GEN-LAST:event_playBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void simulationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card7");
    }//GEN-LAST:event_simulationBtnActionPerformed

    private void howToPlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
    }//GEN-LAST:event_howToPlayBtnActionPerformed

    private void creditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");

        CardLayout c1 = (CardLayout) (cardLayoutPanel.getLayout());
        c1.show(cardLayoutPanel, "card17");
    }//GEN-LAST:event_creditBtnActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       
        /** TODO add your handling code here:
        playSound("ButtonSound.wav");

        String nome;
        Iterator itr;
        String x = "<html>";
        Aposento pe;
        try {
            nome = "";

            itr = teste.unreachableUsers(teste.getVertex(nome));
            while (itr.hasNext()) {
                pe = (Pessoa) itr.next();
                x = x + " id:" + pe.getId() + " nome:" + pe.getNome() + " idade:" + pe.getIdade() + " email:" + pe.getEmail() + "<br/>";
            }
            x = x + "</html>";
            jLabel35.setText(x);
        } catch (Exception e) {
            System.out.println("Não foram inseridos ids");
        }
        **/
    }//GEN-LAST:event_jButton17ActionPerformed

    private void grafoConexoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafoConexoBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        if (teste.isConnected()) {
            grafoConexoLabel.setText("Conexo");
        } else {
            grafoConexoLabel.setText("Não conexo");
        }
    }//GEN-LAST:event_grafoConexoBtnActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        pathLabel.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_fileChooserActionPerformed

    private void sendJsonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJsonBtnActionPerformed
        // TODO add your handling code here:
        playSound("ButtonSound.wav");
        fileSuccessLabel.setVisible(true);
    }//GEN-LAST:event_sendJsonBtnActionPerformed

    private void sendJsonBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendJsonBtnMouseClicked
        // TODO add your handling code here:
        FileManager fm = new FileManager();
        int i = 0, j = 0;
        Game game = fm.readFile(pathLabel.getText());

        while (i < map.length) {
            teste.addVertex(map[i]);
            i++;
        }

        teste.calculateWeigth();
    }//GEN-LAST:event_sendJsonBtnMouseClicked

    private void pathLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathLabelActionPerformed

    private void pathLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathLabelMouseClicked
        int returnvalue = jFileChooser1.showOpenDialog(null);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            pathLabel.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_pathLabelMouseClicked

    private void simulationStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationStartBtnActionPerformed
        // TODO add your handling code here:
        String nome1, nome2;
        Iterator itr;
        String x = "<html>";
        Aposento ap;

        nome1="entrada";
        nome2="exterior";

        try {
            itr = teste.iteratorShortestPath(teste.getVertex(nome1), teste.getVertex(nome2));
            while (itr.hasNext()) {
                ap = (Aposento) itr.next();
                x = x + " Aposento:" + ap.getAposento() + " Fantasma:" + ap.getFantasma() + " Ligacoes:" + ap.getLigacoes()+ "<br/>";
            }
            x = x + "</html>";
            simulationLabel.setText(x);
        } catch (Exception e) {
            System.out.println("Algo de inesperado aconteceu na simulação!");
        }
    }//GEN-LAST:event_simulationStartBtnActionPerformed

    private void simulationStartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationStartBtnMouseClicked

    }//GEN-LAST:event_simulationStartBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HauntedFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel caminhoSimulationLabel;
    private javax.swing.JPanel cardLayoutPanel;
    private javax.swing.JButton carregarJsonBtn;
    private javax.swing.JButton creditBtn;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel fileChooserPanel;
    private javax.swing.JLabel fileSuccessLabel;
    private javax.swing.JButton grafoConexoBtn;
    private javax.swing.JLabel grafoConexoLabel;
    private javax.swing.JPanel grafoConexoPanel;
    private javax.swing.JButton howToPlayBtn;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jsonFileUploadPanel;
    private javax.swing.JLabel jsonFileViewerLabel;
    private javax.swing.JPanel jsonFileViewerPanel;
    private javax.swing.JLabel jsonViewerTitleLabel;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel loadGameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField pathLabel;
    private javax.swing.JButton playBtn;
    private javax.swing.JLabel playGameLabel;
    private javax.swing.JLabel ricardoLabel;
    private javax.swing.JButton roomsGhostsBtn;
    private javax.swing.JButton secretRoomsBtn;
    private javax.swing.JButton sendJsonBtn;
    private javax.swing.JButton simulationBtn;
    private javax.swing.JLabel simulationLabel;
    private javax.swing.JButton simulationStartBtn;
    private javax.swing.JLabel simulationTitleLabel;
    private javax.swing.JButton titleBtn;
    private javax.swing.JLabel uploadJsonLabel;
    private javax.swing.JButton verJsonBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
