/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author vmvs0
 */
public class JFrameCredits extends javax.swing.JPanel {

    /**
     * Creates new form JFrameCredits
     */
    public JFrameCredits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditMainPanel = new javax.swing.JPanel();
        gameDevByLabel = new javax.swing.JLabel();
        ricardoLabel = new javax.swing.JLabel();
        vitorLabel = new javax.swing.JLabel();

        creditMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        gameDevByLabel.setFont(new java.awt.Font("October Crow", 0, 48)); // NOI18N
        gameDevByLabel.setForeground(new java.awt.Color(255, 0, 0));
        gameDevByLabel.setText("GAME DEVELOPED BY:");

        ricardoLabel.setFont(new java.awt.Font("October Crow", 0, 36)); // NOI18N
        ricardoLabel.setForeground(new java.awt.Color(255, 0, 0));
        ricardoLabel.setText("RICARDO PEREIRA - 8170495");

        vitorLabel.setFont(new java.awt.Font("October Crow", 0, 36)); // NOI18N
        vitorLabel.setForeground(new java.awt.Color(255, 0, 51));
        vitorLabel.setText("VITOR M. SANTOS - 8170312");

        javax.swing.GroupLayout creditMainPanelLayout = new javax.swing.GroupLayout(creditMainPanel);
        creditMainPanel.setLayout(creditMainPanelLayout);
        creditMainPanelLayout.setHorizontalGroup(
            creditMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditMainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(gameDevByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(creditMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creditMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vitorLabel)
                    .addComponent(ricardoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creditMainPanelLayout.setVerticalGroup(
            creditMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameDevByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(ricardoLabel)
                .addGap(18, 18, 18)
                .addComponent(vitorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

        
    public static void main(String args[]) {

        //Script começa aqui
        System.out.println("_______________ Credits Shown _______________");

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCredits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel creditMainPanel;
    private javax.swing.JLabel gameDevByLabel;
    private javax.swing.JLabel ricardoLabel;
    private javax.swing.JLabel vitorLabel;
    // End of variables declaration//GEN-END:variables
}